# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [1]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [2]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidim = np.array([1,2,3,4,5])

# O un array de dos dimensiones (bidimensional)
array_bidim = np.array([[1,2,3],
                        [4,5,6]])

# O un array de tres dimensiones (tridimensional)
array_tridim = np.array([[[1,2,3],
                        [4,5,6]],
                        [[7,8,9],
                        [-4,-5,-6]]])

print(array_unidim)
print(array_bidim)
print(array_tridim)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [-4 -5 -6]]]


Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [5]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
print(array_unidim.shape)
print(array_unidim.ndim)
print(array_unidim.dtype)
print(array_unidim.size)
print(type(array_unidim))

(5,)
1
int32
5
<class 'numpy.ndarray'>


In [6]:
# Atributos del array bidimensional
print(array_bidim.shape)
print(array_bidim.ndim)
print(array_bidim.dtype)
print(array_bidim.size)
print(type(array_bidim))

(2, 3)
2
int32
6
<class 'numpy.ndarray'>


In [7]:
# Atributos del array tridimensional
print(array_tridim.shape) # Primero viene la profundidad, luego el alto y finalmente el ancho
print(array_tridim.ndim)
print(array_tridim.dtype)
print(array_tridim.size)
print(type(array_tridim))

(2, 2, 3)
3
int32
12
<class 'numpy.ndarray'>


In [8]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd
df = pd.DataFrame(array_bidim)
df

0  1  2
0  1  2  3
1  4  5  6

In [9]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4, 3)) #4 es el alto y 3 es el ancho
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
ceros = np.zeros((2,4,3)) # 2 de profundidad, 4 de alto y tres de ancho
ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0,100,5)
array_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [16]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0,10, (2,5))
array_2

array([[5, 0, 4, 6, 5],
       [3, 6, 2, 1, 3]])

In [17]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
array_3 = np.random.random((3,5))
array_3

array([[0.85598407, 0.65176882, 0.86693885, 0.28341997, 0.13968729],
       [0.80924534, 0.99414885, 0.47498122, 0.48461907, 0.7776508 ],
       [0.37848541, 0.99882376, 0.54970612, 0.04788137, 0.99717712]])

In [19]:
# Establecemos la "semilla" de números aleatorios en 27. El random realizadó será siempre el mismo más allá de cuantas veces lo volvamos a ejecutar!!! 
np.random.seed(27)

# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0,10, (3, 5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [20]:
# Encontramos los valores únicos del array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [21]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [22]:
# Extraemos las primeras dos filas del array_4
array_4[0:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [23]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[0:2, 0:2]

array([[3, 8],
       [5, 8]])

In [26]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0,10, (3, 4))
print(array_5)

array_6 = np.ones((3, 4))
print(array_6)

[[1 1 7 0]
 [7 8 4 9]
 [0 4 7 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# invocamos el array_5
array_5

array([[1, 1, 7, 0],
       [7, 8, 4, 9],
       [0, 4, 7, 0]])

In [28]:
# invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# Sumamos los dos arrays
array_5 + array_6

array([[ 2.,  2.,  8.,  1.],
       [ 8.,  9.,  5., 10.],
       [ 1.,  5.,  8.,  1.]])

In [30]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
# Intentaremos sumar los arrays 6 y 7
array_6 + array_7

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [33]:
# Si tranpongo  las filas por las columnas entonces si podría:
array_6 + array_7.T

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [35]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4, 3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# Restamos el array_8 al array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))

In [46]:
# invocamos el array_9
array_9

array([[4, 2, 2],
       [2, 1, 2],
       [2, 2, 3]])

In [47]:
# invocamos el array_10
array_10

array([[4, 3, 3],
       [3, 2, 3],
       [2, 1, 4]])

In [44]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10

array([[16,  6,  6],
       [ 6,  2,  6],
       [ 4,  2, 12]])

In [48]:
# Elevamos el array_9 al cuadrado
array_9 ** 2

array([[16,  4,  4],
       [ 4,  1,  4],
       [ 4,  4,  9]])

In [49]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[2.        , 1.73205081, 1.73205081],
       [1.73205081, 1.41421356, 1.73205081],
       [1.41421356, 1.        , 2.        ]])

In [50]:
# Hallamos el promedio de los valores del array_9
array_9.mean()

2.2222222222222223

In [51]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

4

In [52]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

1

In [53]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
array_11 = array_9.reshape((9, 1))
array_11

array([[4],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [3]])

In [ ]:
# invocamos el array_11
array_11

In [54]:
# Transponemos el array_11
array_11.T

array([[4, 2, 2, 2, 1, 2, 2, 2, 3]])

In [56]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

¿Qué tipos de datos forman parte del array de resultados?

In [58]:
# Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [59]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[ True, False, False],
       [False, False, False],
       [ True, False, False]])

In [60]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10

array([[ True, False, False],
       [False, False, False],
       [ True,  True, False]])

In [64]:
# Buscamos los elementos del array_9 que son mayores a 2
array_12 = array_9 > 2
for bool_sub_array, sub_array in zip(array_12, array_9):
    for bool_scalar, scalar in zip(bool_sub_array, sub_array):
        if bool_scalar == True:
            print(scalar)

True
4
False
2
False
2
False
2
False
1
False
2
False
2
False
2
True
3


In [ ]:
# Ordenamos de menor a mayor los elementos dentro del array_9